### ISSUE TITLE
Backport fix manifest incompatibility in ModelMesh labels

### ISSUE THREAD

**Issue by danielezonca** [opendatahub-io/modelmesh#29] opened 2023-07-20 14:45 UTC

**Comment by danielezonca** [comment] 2023-07-20 14:46
- https://github.com/red-hat-data-services/odh-manifests/pull/418
- https://github.com/red-hat-data-services/odh-manifests/pull/417

**Comment by heyselbi** [comment] 2023-07-26 16:54
@danielezonca If the issue is resolved now, should we close it up?

**Closed** 2023-07-26 17:13 UTC
